name: E2 - Realizar la ejecución de 3 tareas secuenciales (configuración, construcción y prueba)

on:
  push:
    branches: [ main ]
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Configuracion - Obteniendo el repositorio
        uses: actions/checkout@v2
      - name: Configuracion - Instalando node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.6
      - name: Configuracion - Instalando yarn
        run: mkdir logs && npm install -g yarn >> logs/index.html  
      - name: Install Yarn
        run: ls -la  
      - name: Construyendo - Intalando dependencias
        run: yarn install
      
      - name: Construyendo - Build
        run: yarn build 2>&1 >> logs/index.html
      
      - name: Probando - Ejecutando test01 
        run: yarn test01 2>&1 >> logs/index.html
      - name: show
        run: ls -la
        
      - name: Log surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'gonzalo-ci-cd.surge.sh'
          project: './logs/'
          login: 'goh.acm@gmail.com'
          token: '87c635c437ce9798c9f57e9327607980'
