
  
name: E5 - Ejecutar 3 runners, mostrar las caracteristicas, recursos y direccion IP

on:
  push:
    branches:
      - main
jobs:
  job-05:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, ubuntu-20.04]    
    steps:
      - name: Mostrar SW
        run: cat /etc/*-release
      - name: Mostrar HW
        run: lscpu        
      - name: Mostrar IP
        run: ip a
