name: E2 - Realizar la ejecución de 3 tareas secuenciales (configuración, construcción y prueba)

on:
  push:
    branches: [ main ]
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Configuracion - Obteniendo el repositorio
        uses: actions/checkout@v2
      - name: Configuracion - Instalando node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.22.6
      - name: Configuracion - Instalando yarn
        run: mkdir logs && npm install -g yarn > logs/index.html  
      - name: Construyendo - Intalando dependencias
        run: yarn install      
      - name: Construyendo - Build
        run: yarn build >> logs/index.html      
      - name: Probando - Ejecutando test01 
        run: yarn test01 >> logs/index.html        
      - name: Almacenando logs en un servidor web con surge.sh gonzalo-ci-cd-surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'gonzalo-ci-cd.surge.sh'
          project: './logs/'
          login: 'goh.acm@gmail.com'
          token: '87c635c437ce9798c9f57e9327607980'
